site_name:        "Test"
site_author:      "redtide"
site_url:         "https://redtide.github.io/mkdocs-test"
site_dir:         "_site_mkdocs"
site_description: "MKDocs test site"

repo_name:        "GitHub"
repo_url:         "https://github.com/redtide/mkdocs-test"
edit_uri:         "edit/master/docs/"
remote_branch:    "www"

docs_dir: "docs"
copyright: "redtide"

extra:
  site_web_author: "redtide"
  repo_owner_url:  "https://github.com/redtide"
  repo_branch:     "master"

markdown_extensions:
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_png
    alt: short
    options:
      attributes:
        align: absmiddle
        height: 20px
        width: 20px
plugins:
  search: {}
  blogging:
    dirs:
    - news/posts
    locale: en
    paging: true
    full_content: true
    show_total: false
    size: 5
    meta_time_format: "%Y-%m-%d %H:%M:%S"
    time_format: "%Y-%m-%d %H:%M:%S"

theme:
  name:        null
  custom_dir: "custom_theme"
  highlightjs: true
  hljs_light: "github"
  hljs_dark:  "github-dark"
  nav_style:  "dark"
  locale:     "en"
  bootstrap_version: "5.3.0"
  shortcuts:
    help:     191 # ?
    next:      78 # n
    previous:  80 # p
    search:    83 # s

watch:
- docs
- custom_theme
